export {Avatar1} from "./components/Avatar"
export {Button} from "./components/Button"
export {Cards} from "./components/Card"
export {Checkbox1} from "./components/Checkbox"
export {Chips} from "./components/Chips"
export {DatePicker} from "./components/DatePicker"
export {Input} from "./components/Input"
export {Label} from "./components/Label"
// export {Modalify} from "./components/Models"
export {Pagination} from "./components/Pagination"
export {ProgressBar} from "./components/ProgressBar"
export {Quantity} from "./components/Quantity"
export {Radio} from "./components/Radio"
export {Ratings} from "./components/Ratings"
export {Selector1} from "./components/Selection_1"
export {Slider1} from "./components/Slider"
export {Switch1} from "./components/Switches"
export {TimePicker} from "./components/TimePicker"
export {Toast} from "./components/Toast"
export {ToolTip} from "./components/ToolTip"
export {Upload} from "./components/UploadFile"
export {Modal} from "./components/Modal2"


export {Body1} from "./components/typography/Body1"
export {Body2} from "./components/typography/Body2"
export {ButtonLg} from "./components/typography/ButtonLg"
export {ButtonMd} from "./components/typography/ButtonMd"
export {ButtonSm} from "./components/typography/ButtonSm"
export {Caption1} from "./components/typography/Caption1"
export {Caption2} from "./components/typography/Caption2"
export {H1} from "./components/typography/Heading1"
export {H2} from "./components/typography/Heading2"
export {H3} from "./components/typography/Heading3"
export {H4} from "./components/typography/Heading4"
export {H5} from "./components/typography/Heading5"
export {H6} from "./components/typography/Heading6"
export {Subtitle1} from "./components/typography/Subtitle1"
export {Subtitle2} from "./components/typography/Subtitle2"

